"""empty message

Revision ID: 188c6180a5f8
Revises: cb125447489d
Create Date: 2019-01-10 12:34:45.401546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188c6180a5f8'
down_revision = 'cb125447489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('locationID', sa.Integer(), nullable=True))
    op.add_column('instances', sa.Column('status', sa.String(length=250), nullable=True))
    op.create_foreign_key(None, 'instances', 'locations', ['locationID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instances', type_='foreignkey')
    op.drop_column('instances', 'status')
    op.drop_column('instances', 'locationID')
    # ### end Alembic commands ###
