"""empty message

Revision ID: 53c9f816694b
Revises: 4bb32258d130
Create Date: 2019-01-06 15:52:54.993652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c9f816694b'
down_revision = '4bb32258d130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('has_tags_ibfk_2', 'has_tags', type_='foreignkey')
    op.drop_constraint('has_tags_ibfk_1', 'has_tags', type_='foreignkey')
    op.create_foreign_key(None, 'has_tags', 'devices', ['deviceID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'has_tags', 'tags', ['tagID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'has_tags', type_='foreignkey')
    op.drop_constraint(None, 'has_tags', type_='foreignkey')
    op.create_foreign_key('has_tags_ibfk_1', 'has_tags', 'devices', ['deviceID'], ['id'])
    op.create_foreign_key('has_tags_ibfk_2', 'has_tags', 'tags', ['tagID'], ['id'])
    # ### end Alembic commands ###
