"""empty message

Revision ID: 81871bba22ae
Revises: 188c6180a5f8
Create Date: 2019-02-25 01:21:02.841411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81871bba22ae'
down_revision = '188c6180a5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorys', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventorys', 'inventorys', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventorys', type_='foreignkey')
    op.drop_column('inventorys', 'parent_id')
    # ### end Alembic commands ###
