"""empty message

Revision ID: 8b5988983160
Revises: 390af3535dcb
Create Date: 2019-01-06 16:05:09.273602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5988983160'
down_revision = '390af3535dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventorys_ibfk_1', 'inventorys', type_='foreignkey')
    op.create_foreign_key(None, 'inventorys', 'devices', ['deviceID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventorys', type_='foreignkey')
    op.create_foreign_key('inventorys_ibfk_1', 'inventorys', 'devices', ['deviceID'], ['id'])
    # ### end Alembic commands ###
