"""empty message

Revision ID: 9544e6fc392b
Revises: 4f2f41dbeee1
Create Date: 2019-02-25 04:25:13.370508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9544e6fc392b'
down_revision = '4f2f41dbeee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventorys', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorys', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
