"""empty message

Revision ID: 9a0a49dc0bed
Revises: ed6882205b65
Create Date: 2019-02-25 03:24:02.003168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a0a49dc0bed'
down_revision = 'ed6882205b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventorys', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('inventorys_ibfk_2', 'inventorys', type_='foreignkey')
    op.create_foreign_key(None, 'inventorys', 'groups', ['group_id'], ['id'])
    op.drop_column('inventorys', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorys', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventorys', type_='foreignkey')
    op.create_foreign_key('inventorys_ibfk_2', 'inventorys', 'inventorys', ['parent_id'], ['id'])
    op.drop_column('inventorys', 'group_id')
    op.drop_table('groups')
    # ### end Alembic commands ###
