"""empty message

Revision ID: a06ac6f86035
Revises: 0630fb5b9de4
Create Date: 2019-01-07 00:07:14.991460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06ac6f86035'
down_revision = '0630fb5b9de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('locationID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'locations', ['locationID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'locationID')
    # ### end Alembic commands ###
