"""empty message

Revision ID: a1ad7a9ebfdb
Revises: b388ba69a643
Create Date: 2019-01-07 01:37:27.980495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ad7a9ebfdb'
down_revision = 'b388ba69a643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
