"""empty message

Revision ID: a6487d30e19e
Revises: a06ac6f86035
Create Date: 2019-01-07 00:33:26.471153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6487d30e19e'
down_revision = 'a06ac6f86035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_hasEvents',
    sa.Column('jobID', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eventID'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jobID'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jobID', 'eventID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_hasEvents')
    op.drop_table('events')
    # ### end Alembic commands ###
