"""empty message

Revision ID: b388ba69a643
Revises: a6487d30e19e
Create Date: 2019-01-07 00:45:50.218906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b388ba69a643'
down_revision = 'a6487d30e19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('endDate', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('startDate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'startDate')
    op.drop_column('events', 'endDate')
    # ### end Alembic commands ###
