"""empty message

Revision ID: cb125447489d
Revises: a1ad7a9ebfdb
Create Date: 2019-01-08 13:34:14.566250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb125447489d'
down_revision = 'a1ad7a9ebfdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('title', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'title')
    # ### end Alembic commands ###
